name: crashPaperPlugin
main: dev.crash.Main
version: 0.1
description: Nix lol
api-version: 1.17
author: Crashcrafter_LP
depend: [Votifier]

commands:
  back:
    description: Back to last death point
    usage: /back
    permission: crash.back
  reloaddb:
    description: reload DB
    usage: /reloaddb
    permission: crash.reloaddb
  reloaduser:
    description: Reload a user
    usage: /reloaduser
    permission: crash.reloaddb
  rank:
    description: Manage Roles
    usage: </command>
    permission: crash.rank
  discord:
    description: Send Discord link
    usage: /discord
  claim:
    description: Claim Chunk & Manage your claims
    usage: </command>
    aliases: [c]
  key:
    description: Key commands
    usage: /key create [type] [amount]
    permission: crash.key
  ci:
    description: Get custom items
    usage: /ci [itemname as in ci.json]
    permission: crash.ci
  tempban:
    description: Tempban player
    usage: /tempban [player] [amount] [timeunit] [Reason]
    permission: crash.tempban
  home:
    description: Teleport to homepoint
    usage: /home [name]
    aliases: [h]
  sethome:
    description: Set homepoint
    usage: /sethome [name]
  delhome:
    description: Delete homepoint
    usage: /delhome [name]
  homes:
    description: Show your homepoints
    usage: /homes
  warn:
    description: Warnt einen User
    usage: /warn [player] [reason]
    permission: crash.warn
  invsee:
    description: Show Inventory of Player
    usage: /invsee [player]
    permission: crash.invsee
  tpa:
    description: TPA to a player
    usage: /tpa [player]
    permission: crash.tpa
  tpaccept:
    description: Accept a TPA request
    usage: /tpaccept
    permission: crash.tpa
  tpdeny:
    description: Deny a TPA request
    usage: /tpdeny
    permission: crash.tpa
  invec:
    description: Show ender chest of a player
    usage: /invec [player]
    permission: crash.invec
  ec:
    description: Show your ender chest
    usage: /ec
    permission: crash.ec
  credits:
    description: Manage your credits
    usage: /credits
    aliases: [cr]
  multiv:
    description: Manage multiworld
    usage: /multiv create [new World name] [Dimension] [WorldGenType] [seed]
    permission: crash.multiv
  drop:
    description: Drop commands
    usage: /drop [args]
    permission: crash.drop
  modchat:
    description: Modchat
    usage: /mc [message]
    permission: crash.modchat
    aliases: [staffchat, mc]
  vote:
    description: Voting
    usage: /vote
  quests:
    description: Quest-Overview
    usage: /quests
    aliases: [q]
  exp:
    description: Level management
    usage: /exp [add/remove] [amount] [XP/Level]
    permission: crash.exp
  profile:
    description: Show player profile
    usage: /profile [Player]
  m:
    description: Private message
    usage: /m [player] message
    aliases: [msg, say, tell]
  weekly:
    description: Claim weekly Keys
    usage: /weekly
  mute:
    description: Mute player
    usage: /mute [player]
    permission: crash.mute
  unmute:
    description: Unmute player
    usage: /unmute [player]
    permission: crash.unmute
  crypto:
    description: Show current crypto prices
    usage: /crypto
  checkitem:
    description: Info about current item
    usage: /checkitem
    permission: crash.checkitem
  guild:
    description: Guild Commands
    usage: /guild
    aliases: [g]
  warp:
    description: Teleport to warppoints
    usage: /warp [name]
    permission: crash.warp
    aliases: [w]

permissions:
  crash.reloaddb:
    description: Can reload DB
    default: op
  crash.back:
    description: Can teleport to death pos after death
    default: true
  crash.tpa:
    description: Can use the TPA-System
    default: true
  crash.rank:
    description: Can change ranks
    default: op
  crash.key:
    description: Can manage keys
    default: op
  crash.ci:
    description: Can generate custom items
    default: op
  crash.tempban:
    description: Can tempban user
    default: op
  crash.warn:
    description: Can warn player
    default: op
  crash.invsee:
    description: See other players inventories
    default: op
  crash.invec:
    description: See other players ender chest
    default: op
  crash.ec:
    description: Access the ender chest
    default: op
  crash.multiv:
    description: Multiworld
    default: op
  crash.drop:
    description: Manage drops
    default: op
  crash.modchat:
    description: Read/Write to the Teamchat
    default: op
  crash.exp:
    description: Manage player levels
    default: op
  crash.mute:
    description: Mute players
    default: op
  crash.unmute:
    description: Unmute players
    default: op
  crash.checkitem:
    description: Check items
    default: op
  crash.warp:
    description: Can use warp commands
    default: true
  crash.setwarp:
    description: Can set/delete warp points
    default: op